### ISSUE TITLE
Stationary solution ensuring a fixed Omega

### ISSUE THREAD

**Issue by jlperla** [jlperla/PerlaTonettiWaugh.jl#316]
Take the initial `Ω_0` and `ζ_0` as given.

For a `ζ`, we need to solve it, modifying the `χ` until the resulting `Ω = Ω_0`.  i.e. whatever the solution is for `g` it will have the same `Ω` as the original one.  To do this, you will probably need to run a root finder over the value.

Once you have that, display a crude grid of `ζ` around the baseline `ζ_0`

**Comment by jlperla** [comment]
I don't this this was working correctly.  In part, you were doing a grid of zeta which didn't include the interior values.

Try the following as a starting point.
```julia
params_base = parameter_defaults(γ = 2.0, ζ = 0.5)
χ_0 = params_base.χ
ζ_0 = params_base.ζ
settings = settings_defaults()
ζ_grid = range(0.01, 1.0, length = 40)
g_grid = similar(ζ_grid)
U_bar_grid = similar(ζ_grid)
Ω_grid = similar(ζ_grid)
for i in 1:length(ζ_grid)
    param = merge(params_base, (ζ = ζ_grid[i], d = params_base.d_0))
    try
        sol = stationary_algebraic(param, settings)
        g_grid[i] = sol.g
        U_bar_grid[i] = sol.U_bar
        Ω_grid[i] = sol.Ω
    catch
        g_grid[i] = NaN
        U_bar_grid[i] = NaN
        Ω_grid[i] =  NaN
    end
end
plot(ζ_grid, [U_bar_grid, Ω_grid, g_grid], layout=3)
```
But modify to your hearts content.  A few things:
- Lets stick with gamma = 2.0 for now, though I want to try higher later.
- You will notice that the Omega grows rapidly in the lower zeta regions, so I would expect things to change if you adjust chi until it is constant.
- There is something weird going on with the convergence for the increased gamma here (which is necessary for the solution).  I think you need to figure that out first why the solution wasn't rejected.  I suggest going through the generated output from a call in that region (e.g. at , `ζ=0.2` and seeing if anything is suspicious).
    - Try the same things with the stationary numerical solution to see if they are different.
    - If there is any other reason to reject the solution, add in the code to the stationary solution as an error (in the same way as it dies if it doesn't converge).
- I think the code would be better if instead of having vectors, you push valid solutions onto a dataframe and then plotted columns of the dataframe.

**Comment by arnavs** [comment]
@jlperla I'm closing since we were able to get it done with the numerical one. See `welfare-investigations.jmd` and related notebook. 

Will open a separate issue for the continued investigation of the discontinuity.
