### ISSUE TITLE
Try to solve for planning solution

### ISSUE THREAD

**Issue by jlperla** [jlperla/PerlaTonettiWaugh.jl#319]
The planner should be able to directly manipulate the Omega, z_hat, and g to maximize the welfare subject to the resource constraints.

I think that means you can just call https://github.com/jlperla/PerlaTonettiWaugh.jl/blob/master/src/full/stationary.jl#L25-L34

Trying different `vals = [g, z_hat, Omega]` to maximize `U_bar`?

**Comment by jlperla** [comment]
Try out the objective with forwarddiff first.

**Comment by arnavs** [comment]
I checked in the plots for a univariate problem (planner picks `g`, while `z_hat, Omega` are fixed at the competitive equilibrium.) 

It looks pretty good. Figure these may be useful to you while I generalize to two dimensions. 

Mainly we saw some instability/dropped values around `d_0`, but lowering it a bit worked.

**Comment by arnavs** [comment]
Closing this. I double checked the consumption equivalents and they are reasonable given our welfare numbers.

https://github.com/jlperla/PerlaTonettiWaugh.jl/blob/master/welfare.ipynb is the link with all the plots and code.
