### ISSUE TITLE
Solve welfare/planning for gamma = 2

### ISSUE THREAD

**Issue by jlperla** [jlperla/PerlaTonettiWaugh.jl#320]
Can you do the same exercise (in the same notebook) in https://github.com/jlperla/PerlaTonettiWaugh.jl/blob/master/welfare.jmd  but with gamma = 2?
If the competitive solution with that doesn't solve, then tell me and I can help you fudge the setup.  e.g. we can increase rho  if required.

**Comment by arnavs** [comment]
Yeah, the competitive for this is breaking. 

Where should we put `rho`? If I jack it up too high (say, `0.04`, from its current `0.0215`), the error goes from "exponential error" (implying one calculation was invalid) to just a straight "solver didn't converge."
