### ISSUE TITLE
Prep for constrained planning problem with chi, etc.

### ISSUE THREAD

**Issue by jlperla** [jlperla/PerlaTonettiWaugh.jl#324]
The goal of this is to allow a planner to distort the `ζ` and `χ`, call them `χ_p` and `ζ_p` (for planner) which they are able to manipulate through lump-sum taxes.

The basic economics is that we can replace any  `ζ` with `ζ_p` and `χ` with `χ_p` in any direct firm decisions/FOCs, but anything that involves a resource constraint of the economy needs to use  `ζ` and `χ`.

So, in a PR,
- [x] Add in parameters https://github.com/jlperla/PerlaTonettiWaugh.jl/blob/master/src/full/params.jl#L2
  -  Maybe have them default as ``ζ_p = ζ` and `χ_p= χ` at the end of the named tuple?  That way we can fully nest things?
- [x] I think we need to have two version of `x` now.... one faced by the firm and one in the resource constraint.
  - To do this, lets take the current `x()` function and add the parameter
  - i.e. https://github.com/jlperla/PerlaTonettiWaugh.jl/blob/master/src/full/static.jl#L22-L25 becomes 
```julia
function x(w, ζ, parameters)
    @unpack Theta, η = parameters
    return ζ * (1 - η + η * Theta / w) # (C.14)
end
```
- [x] Go to all the places which use the `x` and we will then need to manually figure out whether it is `ζ` or `ζ_p`.
  - https://github.com/jlperla/PerlaTonettiWaugh.jl/blob/master/src/full/stationary.jl#L67  should use `ζ`
  - We need to remember that https://github.com/jlperla/PerlaTonettiWaugh.jl/blob/master/src/full/stationary.jl#L71 passes back the "real" x.
  - Strip out the `x` from https://github.com/jlperla/PerlaTonettiWaugh.jl/blob/master/src/full/stationary.jl#L39  since we want the other one.
- [x] Then make sure that the unit tests still all pass for this.

**Comment by arnavs** [comment]
Test cases all pass.
