### ISSUE TITLE
Externalities experiment

### ISSUE THREAD

**Issue by jlperla** [jlperla/PerlaTonettiWaugh.jl#331]
- [x] First, lets display the key equilibrium values for the two `d` cases.
  - Call them `d_baseline` for the `d_0` case, etc. and `d_open` for the `d_T` ones
  - In particular, calculate `U_bar_, g_, λ_ii_, c_, y_, Omega_, z_hat_` for all of the cases.
- [x] Display `d_U_bar = U_bar_open - U_bar_baseline` in a cell
- [x] Now, what we want to do is calculate the equilibrium with the `d_T` parameters, but holding `g = g_baseline` fixed.  That is something like
```
sol = stationary_algebraic_given_g(g_baseline, parameters_open, settings) # i.e. parameters uses d_T, not d_0
c_partial = sol.c
```
- [x] Using that, define
```julia
dc = (c_partial - c_baseline)/(d_T - d_0)
```
- In another cell, define
```julia
d_U_1 = 1/(c_baseline * rho)
```
- [x] Finally, the number we are interested in is
```julia
d_U_bar - d_U_1  * dc
```
@CTonetti  Lets review this all carefully to make sure I didn't mess up a sign or swap the order.

**Comment by CTonetti** [comment]
In the finite difference approximation for d_U_bar, that is, d_U_bar = U_bar_open - U_bar_baseline, should we divide by (d_T-d_0), just like we do in the definition of dc? Not sure, but I think we either divide both (more correct) or don't divide in both (equivalent approach for our final number of interest). Otherwise, looks correct to me. Fingers crossed.

**Comment by jlperla** [comment]
Yes, that is a mistake.  @arnavs  note:
```
d_U_bar = (U_bar_open - U_bar_baseline)/(d_T - d_0)
```

**Comment by arnavs** [comment]
Noted.

**Comment by jlperla** [comment]
@arnavs  Maybe have a separate cell where we do the calculation without any divisions.  i.e.
```
d_U_bar = U_bar_open - U_bar_baseline
dc = c_partial - c_baseline
d_U_bar - d_U_1  * dc
```
The `d_U_1` shouldn't change there.

**Comment by arnavs** [comment]
OK, sounds good.

**Comment by arnavs** [comment]
The number with the divisions is around `-16.4` (for `d_U_bar - d_U_1 * dc`), and without the divisions is around 3.34

**Comment by arnavs** [comment]
Closing this as the notebook etc. is up to date.
