### ISSUE TITLE
Adapt the welfare decomposition to support gamma != 1

### ISSUE THREAD

**Issue by jlperla** [jlperla/PerlaTonettiWaugh.jl#333]
Right now the derivative in https://github.com/jlperla/PerlaTonettiWaugh.jl/blob/master/src/full/stationary.jl#L4-L5 for the welfare is hardcoded based on gamma = 1.  We should have it toggle... so something like: 

```julia
@unpack ρ, d, γ = params_baseline
sol_baseline = stationary_algebraic(params_baseline, settings)
if γ == 1
    U_1 = 1/(ρ*sol_baseline.c)
    U_2 = (1/ρ^2)
else
    U_1 = sol_baseline.c^(-γ) / (ρ + (γ-1)* sol_baseline.g)
    U_2 = sol_baseline.c^(1-γ) * (ρ + (γ-1)* sol_baseline.g)^(-2)
end
```

- [x] Implement that code and make sure it is still generating the `gamma = 1` case correctly.
- [x] Do a small tweak to `gamma`... like `gamma = 1.05` or something like that... and see what numbers you get out of there to see if things break.  If that is too big of a change and things don't converge, then just make it smaller.
  - We do not need to have that calculation in a notebook, just use it to make sure the code seems to work.

@CTonetti  If you want to check the algebra, I differentiated the welfare function and simplified.  The `c` derivative is a joke, and the `g` derivative ended up as the the above, which is hopefully:
![\frac{c^{1-\gamma }}{((\gamma -1) g+\rho )^2}](https://render.githubusercontent.com/render/math?math=%5Cfrac%7Bc%5E%7B1-%5Cgamma%20%7D%7D%7B((%5Cgamma%20-1)%20g%2B%5Crho%20)%5E2%7D)

**Comment by CTonetti** [comment]
@jlperla @arnavs I think derivative math for U_1 and U_2 formula is correct.
